title: Oh look mom!! I did something!
author: HouseholdRat
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Im not awesome so i dont know what to write here.

# social links
twitter_username: Cageandribs # DO NOT include the @ character, or else the build will fail!
github_username:  householdrat # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
